// client2/src/components/_design-system/Header.vue
<template>
  <div class="Header" :class="{ minimized: minimized }">
    <div class="Header-top">
      <div class="Header-top-title">
        <div class="Header-top-title-links">
          <h4>Cabinet d'ostéopathie de Roselyne Lean</h4>
          <Location/>
          <Phone/>
        </div>
        <div class="Header-top-title-hexagons" @click="minimized = !minimized">
          <Hexagon :width="35" image="images/rose.jpg"/>
          <Hexagon :width="35" image="images/anais.jpg"/>
        </div>
      </div>
      <div class="Header-top-menu">
        <Button
          v-for="(menuItem, index) of menuItems"
          class="Header-top-menu-item"
          color="white"
          :icon="menuItem.icon"
          :label="menuItem.label"
          :active="isMenuItemActive(index)"
          :outlined="!isMenuItemActive(index)"
          @click="onMenuItemClicked(menuItem)"
        />
      </div>
    </div>

    <div class="Header-top minimalistic">
      <div class="Header-top-title">
        <h4>Cabinet d'ostéopathie</h4>
        <h4>de Roselyne Lean</h4>
      </div>
      <template v-if="!isOnAdminPage">
        <div class="Header-top-links">
          <Phone :no-text="true"/>
          <Location :no-text="true"/>
          <RouterLink v-if="isPractitioner" class="dark" :to="adminMenuItem.url!">
            <v-icon icon="mdi-cog"/>
          </RouterLink>
        </div>
      </template>
      <template v-else>
        <div class="Header-top-links">
          <RouterLink class="dark" :to="adminMenuItems[0].url!">
            <v-icon icon="mdi-apps"/>
          </RouterLink>
        </div>
      </template>
    </div>

    <HeaderHexagons v-if="!minimized"/>
  </div>
</template>

<script lang="ts">
import RoutePath from "@shared/types/route.enum";
import AuthenticationHttpService from "../../services/http/authentication.http-service";
import {Role} from "@shared/types/role.enum";
import {Component, Emit, Vue} from "vue-facing-decorator";
import type {HeaderMenuItem} from "@/components/_design-system/types";
import Hexagon from "@/components/_design-system/Hexagon.vue";
import {Container} from "typedi";
import HeaderHexagons from "@/components/_design-system/HeaderHexagons.vue";
import Phone from "@/components/_design-system/Phone.vue";
import Location from "@/components/_design-system/Location.vue";
import Button from "@/components/_design-system/Button.vue";

@Component({
  components: {Button, Location, Phone, HeaderHexagons, Hexagon}
})
export default class Header extends Vue {
  private readonly authenticationHttpService = Container.get(AuthenticationHttpService)

  minimized = false
  appMenuItems: HeaderMenuItem[] = [
    { label: 'Prendre rendez-vous', icon: 'mdi-calendar', command: () => this.toggleMinimization() },
    { label: 'Infos pratiques', icon: 'mdi-map-marker', command: () => this.clickInfosMenuItem() },
    { label: 'L\'ostéopathie', icon: 'mdi-help', command: () => this.clickOsteopathyMenuItem() },
  ]
  adminMenuItems: HeaderMenuItem[] = [
    { label: 'App', icon: 'mdi-apps', url: RoutePath.APP },
    { label: 'Admin', icon: 'mdi-cog', url: RoutePath.ADMIN }
  ]
  adminMenuItem: HeaderMenuItem = { label: 'Admin', icon: 'mdi-cog', url: RoutePath.ADMIN }

  get path(): string {
    return this.$router.currentRoute.value.path
  }

  get isOnAdminPage(): boolean {
    return this.path === RoutePath.ADMIN
  }

  get isPractitioner(): boolean {
    return this.authenticationHttpService.isAuthenticated(Role.PRACTITIONER)
  }

  get menuItems(): HeaderMenuItem[] {
    if (this.isOnAdminPage) {
      this.minimized = true
      return this.adminMenuItems
    }
    if (!this.isPractitioner) {
      return this.appMenuItems
    }
    return [
      ...this.appMenuItems,
      this.adminMenuItem
    ]
  }

  @Emit()
  clickInfosMenuItem() {
  }

  @Emit()
  clickOsteopathyMenuItem() {
  }

  onMenuItemClicked(menuItem: HeaderMenuItem) {
    if (menuItem.command) {
      menuItem.command()
    }
    if (menuItem.url) {
      this.$router.push(menuItem.url)
    }
  }

  toggleMinimization() {
    this.minimized = !this.minimized
  }

  isMenuItemActive(index: number): boolean {
    if (this.path === RoutePath.ADMIN) {
      return index === 1
    }
    return index === 0
  }
}
</script>

<style lang="scss">
.Header {
  color: rgba(var(--v-theme-white));
  display: flex;
  flex-direction: column;
  align-items: center;
  background-color: rgba(var(--v-theme-primary));
  border-radius: 0 0 1rem 1rem;
  padding: 1rem;

  h4 {
    margin: 0;
  }

  &-top {
    width: 100%;
    flex-grow: 1;
    display: flex;
    justify-content: space-between;

    &.minimalistic {
      display: none;
    }

    &-title {
      display: flex;
      gap: .5rem;
      flex-direction: column;
      &-links {
        display: flex;
        gap: .3rem;
        flex-direction: column;
        &.minimized {
          display: none;
        }
      }
      &-hexagons {
        display: none;
      }
      .pi {
        margin-right: .5rem;
      }
      a {
        font-size: .8rem;
        color: var(--primary-50);
        font-weight: normal;
      }
    }

    &-menu {
      display: flex;
      align-items: flex-start;
      gap: 1rem;
      text-align: center;
      &-item .pi {
        margin-right: .5rem;
      }
    }
  }

  &-hexagons {
    transition: height .5s ease;
    position: relative;
    display: flex;
    align-items: center;
    justify-content: center;
    margin-bottom: 1rem;
  }
}

.Header.minimized {
  .Header {
    &-top {
      align-items: center;
      &-name {
        display: none;
      }
      &-title {
        flex-direction: row;
        align-items: center;
        &-links.minimized {
          display: block;
        }
        &-links:not(.minimized) {
          display: none;
        }
        &-hexagons {
          display: flex;
          align-items: center;
          gap: 1rem;
          cursor: pointer;
          margin-right: 1rem;
        }
        .pi {
          font-size: 1.2rem;
          border: .5px solid;
          border-radius: 50%;
          padding: .5rem;
        }
      }
    }
  }
}

@media (max-width: 1100px) {
  .Header {
    &-top {
      &:not(.minimalistic) {
        display: none;
      }
      &.minimalistic {
        display: flex;
        align-items: center;
      }

      &-title {
        gap: 0;
        flex-direction: column !important;
        align-items: baseline !important;
      }

      &-links {
        display: flex;
        gap: 1rem;
        .pi {
          font-size: 1.2rem;
          border: .5px solid;
          border-radius: 50%;
          padding: .5rem;
        }
      }
    }

    &-hexagons {
      display: none;
    }
  }
}
</style>

// client/src/components/_shared/header/header.component.ts
import {Component, EventEmitter, Output} from '@angular/core';
import {HexagonComponent} from "../../_design-system/hexagon/hexagon.component";
import {Button} from "primeng/button";
import {TabMenuModule} from "primeng/tabmenu";
import {MenuItem} from "primeng/api";
import {NgClass, NgForOf, NgIf} from "@angular/common";
import {DividerModule} from "primeng/divider";
import RoutePath from "@shared/types/route.enum";
import {Router} from "@angular/router";
import AuthenticationService from "../../../services/authentication.service";
import {Role} from "@shared/types/role.enum";

@Component({
  selector: 'op-header',
  standalone: true,
  imports: [
    HexagonComponent,
    Button,
    TabMenuModule,
    NgForOf,
    DividerModule,
    NgIf,
    NgClass
  ],
  templateUrl: './header.component.html',
  styleUrl: './header.component.scss'
})
export class HeaderComponent {
  @Output() clickInfosMenuItem = new EventEmitter<void>()
  @Output() clickOsteopathyMenuItem = new EventEmitter<void>()
  @Output() clickAdminMenuItem = new EventEmitter<void>()

  minimized = false

  appMenuItems: MenuItem[] = [
    { label: 'Prendre rendez-vous', icon: 'pi pi-fw pi-calendar', command: () => this.minimized = !this.minimized },
    { label: 'Infos pratiques', icon: 'pi pi-fw pi-map-marker', command: () => this.clickInfosMenuItem.emit() },
    { label: 'L\'ostéopathie', icon: 'pi pi-fw pi-question', command: () => this.clickOsteopathyMenuItem.emit() },
  ];
  adminMenuItems: MenuItem[] = [
    { label: 'App', icon: 'pi pi-fw pi-th-large', url: `/${RoutePath.APP}` },
    { label: 'Admin', icon: 'pi pi-fw pi-cog', url: `/${RoutePath.ADMIN}` }
  ];
  adminMenuItem: MenuItem = { label: 'Admin', icon: 'pi pi-fw pi-cog', url: `/${RoutePath.ADMIN}` }

  get path(): string {
    return this.router.url.substring(1)
  }

  get isOnAdminPage(): boolean {
    return this.path === RoutePath.ADMIN
  }

  get isPractitioner(): boolean {
    return this.authenticationService.isAuthenticated(Role.PRACTITIONER)
  }

  get menuItems(): MenuItem[] {
    if (this.isOnAdminPage) {
      this.minimized = true
      return this.adminMenuItems
    }
    if (!this.isPractitioner) {
      return this.appMenuItems
    }
    return [
      ...this.appMenuItems,
      this.adminMenuItem
    ]
  }

  constructor(
    private readonly router: Router,
    private readonly authenticationService: AuthenticationService
  ) {
  }

  isMenuItemActive(index: number): boolean {
    if (this.path === RoutePath.ADMIN) {
      return index === 1
    }
    return index === 0
  }
}

<div class="Header" [ngClass]="{ minimized: minimized }">
  <div class="Header-top">
    <div class="Header-top-title">
      <div class="Header-top-title-links">
        <h4>Cabinet d'ostéopathie de Roselyne Lean</h4>
        <a class="dark" href="https://maps.app.goo.gl/E6vYw1tQbJ8j22Ye6" target="_blank">
          <span class="pi pi-map-marker"></span>
          <span>Village anglais rue Georges Ohnet, 77340 Pontault-Combault</span>
        </a>
        <a class="dark" href="tel://+33695084023">
          <span class="pi pi-phone"></span>
          <span>06 95 08 40 23</span>
        </a>
      </div>
      <div class="Header-top-title-hexagons" (click)="minimized = !minimized">
        <op-hexagon [width]="35" image="images/rose.jpg"/>
        <op-hexagon [width]="35" image="images/anais.jpg"/>
      </div>
    </div>
    <div class="Header-top-menu">
      <a
        *ngFor="let menuItem of menuItems; index as index"
        class="Header-top-menu-item p-button p-button-rounded p-button-sm p-button-icon"
        (click)="menuItem.command ? menuItem.command({ originalEvent: $event, item: menuItem, index}) : undefined"
        [routerLink]="menuItem.url"
        [ngClass]="{
          'p-button-primary': !isMenuItemActive(index),
          'p-button-secondary': isMenuItemActive(index),
          'dark': !isMenuItemActive(index),
        }"
      >
        <i class="pi {{ menuItem.icon }}"></i>
        <span class="Header-top-menu-item-label">{{ menuItem.label }}</span>
      </a>
    </div>
  </div>

  <div class="Header-top minimalistic">
    <div class="Header-top-title">
      <h4>Cabinet d'ostéopathie</h4>
      <h4>de Roselyne Lean</h4>
    </div>
    <ng-container *ngIf="!isOnAdminPage; else headerTopLinksAdmin">
      <div class="Header-top-links">
        <a class="dark" href="tel://+33695084023">
          <span class="pi pi-phone"></span>
        </a>
        <a class="dark" (click)="appMenuItems[1].command!({ originalEvent: $event, item: appMenuItems[1], index: 1})">
          <span class="pi pi-map-marker"></span>
        </a>
        <a *ngIf="isPractitioner" class="dark" [routerLink]="adminMenuItem.url">
          <span class="pi pi-cog"></span>
        </a>
      </div>
    </ng-container>
    <ng-template #headerTopLinksAdmin>
      <div class="Header-top-links">
        <a class="dark" [routerLink]="adminMenuItems[0].url">
          <span class="pi pi-th-large"></span>
        </a>
      </div>
    </ng-template>
  </div>

  <div *ngIf="!minimized" class="Header-hexagons">
    <op-hexagon
      [width]="100"
      [raised]="true"
      image="images/osteo4.jpg"
      style="transform: translateX(20px) translateY(0px)"
    />
    <op-hexagon
      [width]="120"
      [raised]="true"
      image="images/osteo2.jpg"
      style="z-index: 10; transform: translateX(-0px) translateY(30px)"
    />
    <op-hexagon
      [width]="100"
      [raised]="true"
      image="images/osteo3.jpg"
      style="transform: translateX(-20px) translateY(-10px)"
    />
    <div style="z-index: 10; transform: translateX(20px) translateY(-30px)">
      <op-hexagon
        [width]="200"
        [raised]="true"
        image="images/rose.jpg"
      />
      <div style="text-align: center; transform: translateY(20px)">
        Roselyne LEAN
      </div>
    </div>
    <div style="transform: translateX(5px) translateY(-10px)">
      <op-hexagon
        [width]="180"
        [raised]="true"
        image="images/anais.jpg"
      />
      <div style="text-align: center; transform: translateY(10px);">
        Anais DE CARVALHO
      </div>
    </div>
    <op-hexagon
      [width]="100"
      [raised]="true"
      image="images/osteo5.jpg"
      style="transform: translateX(45px) translateY(0px)"
    />
    <op-hexagon
      [width]="120"
      [raised]="true"
      image="images/osteo6.jpg"
      style="z-index: 10; transform: translateX(25px) translateY(-20px)"
    />
    <op-hexagon
      [width]="100"
      [raised]="true"
      image="images/osteo7.jpg"
      style="z-index: 5; transform: translateX(5px) translateY(20px)"
    />
  </div>
</div>
