// client2/src/components/app/Appointment.vue
<template>
  <v-card
    class="pa-6"
    max-width="100vw"
    width="550px"
  >
    <v-card-title class="d-flex">
      <div class="p-dialog-title">
        Créneau du {{ DateHelper.format(slot.from, DateFormat.DATE_TIME) }}
      </div>
      <v-spacer/>
      <IconPractitioner
        :practitioner="slot.practitioner"
        :width="50"
      />
    </v-card-title>
    <v-alert
      v-if="isSlotForChildrenOnly"
      color="warning"
      icon="mdi-alert"
    >
      <template v-slot:text>
        Les créneaux du mercredi sont réservés aux bébés et enfants.
        Pour toute demande urgente, n'hésitez pas à appeler le
        <Phone :with-icon="false"/>
        .
      </template>
    </v-alert>
    <form class="Appointment-form">
      <v-text-field
        v-model="form.lastname"
        variant="outlined"
        label="Nom *"
        :autofocus="false"
        :rules="[(v) => !!v || 'Champ obligatoire']"
        rounded
        @focusout="onFocusOutLastname()"
      />
      <v-text-field
        v-model="form.firstname"
        variant="outlined"
        label="Prénom *"
        :autofocus="false"
        :rules="[(v) => !!v || 'Champ obligatoire']"
        rounded
        @focusout="onFocusOutFirstname()"
      />
      <InputPhone
        @update="onPhoneChanged($event)"
        @focusout="onFocusOutPhone()"
      />
      <v-select
        v-model="form.type"
        variant="outlined"
        label="Type de séance"
        :autofocus="false"
        :items="patientTypeOptions"
        rounded
        @change="onChangedPatientType()"
      />
    </form>
    <v-card-actions>
      <Button
        label="Annuler"
        size="large"
        :active="true"
        @click="cancelAppointment()"
      />
      <Button
        label="Réserver le créneau"
        color="secondary"
        size="large"
        :active="true"
        :disabled="!canBook"
        :loading="isBookingAppointment"
        @click="onBookAppointment()"
      />
    </v-card-actions>
  </v-card>
</template>

<script lang="ts">
import {Component, Emit, Prop, Vue} from "vue-facing-decorator";
import IconPractitioner from "@/components/_design-system/IconPractitioner.vue";
import type {SlotPersisted} from "@shared/types/slot.interface";
import type {Patient} from "@shared/types/patient.interface";
import {isPatientType, PatientType} from "@shared/types/patient.interface";
import AvailabilityHttpService from "@/services/http/availability.http-service";
import ToasterService from "@/services/snackbar/toaster.service";
import AnalyticsPulsarService from "@/services/analytics-pulsar.service";
import {Practitioner} from "@shared/types/practitioner.enum";
import DateHelper from "@shared/helpers/date.helper";
import {isString} from "@shared/helpers/common-types.guards";
import PhoneHelper from "@shared/helpers/phone.helper";
import type {AnalyticsActionDataTypes} from "@shared/types/analytics.types";
import {AnalyticsAction} from "@shared/types/analytics.types";
import InputPhone from "@/components/_design-system/InputPhone.vue";
import {createPatientForm} from "@/forms/patient.form";
import {Container} from "typedi";
import DateFormat from "../../../../shared/types/date-format.enum";
import Button from "@/components/_design-system/Button.vue";
import Phone from "@/components/_design-system/Phone.vue";

@Component({
  components: {Phone, Button, InputPhone, IconPractitioner}
})
export default class Appointment extends Vue {
  @Prop({required: true}) slot!: SlotPersisted

  @Emit()
  cancelAppointment() {
  }

  @Emit()
  appointmentBooked(slot: SlotPersisted, patient: Patient) {
    return {
      slot,
      patient
    }
  }

  private readonly availabilityService = Container.get(AvailabilityHttpService)
  private readonly toasterService = Container.get(ToasterService)
  private readonly analyticsPulsar = Container.get(AnalyticsPulsarService)

  readonly DateFormat = DateFormat
  readonly DateHelper = DateHelper

  isBookingAppointment = false
  form = createPatientForm()

  get isSlotForChildrenOnly(): boolean {
    return (
      this.slot.practitioner === Practitioner.ROSE &&
      DateHelper.isWednesday(this.slot.from)
    )
  }

  get patientTypeOptions(): PatientType[] {
    if (this.isSlotForChildrenOnly) {
      return [
        PatientType.BABY,
        PatientType.CHILD
      ];
    }
    return Object.values(PatientType) as PatientType[]
  }

  get canBook(): boolean {
    return (
      !this.isBookingAppointment &&
      isString(this.form.firstname) &&
      this.form.firstname.length > 0 &&
      isString(this.form.lastname) &&
      this.form.lastname.length > 0 &&
      PhoneHelper.isValidNumber(this.form.phone) &&
      isPatientType(this.form.type)
    )
  }

  mounted() {
    if (this.isSlotForChildrenOnly) {
      this.form.type = this.patientTypeOptions[0]
    }
  }

  onFocusOutLastname() {
    if (!this.form.lastname?.length) {
      return
    }
    const analyticsData: AnalyticsActionDataTypes[AnalyticsAction.APPOINTMENT_LASTNAME_FILLED] = {
      lastname: this.form.lastname
    }
    this.analyticsPulsar.action(AnalyticsAction.APPOINTMENT_LASTNAME_FILLED, analyticsData)
  }

  onFocusOutFirstname() {
    if (!this.form.firstname?.length) {
      return
    }
    const analyticsData: AnalyticsActionDataTypes[AnalyticsAction.APPOINTMENT_FIRSTNAME_FILLED] = {
      firstname: this.form.firstname
    }
    this.analyticsPulsar.action(AnalyticsAction.APPOINTMENT_FIRSTNAME_FILLED, analyticsData)
  }

  onFocusOutPhone() {
    if (!this.form.phone?.length) {
      return
    }
    const analyticsData: AnalyticsActionDataTypes[AnalyticsAction.APPOINTMENT_PHONE_FILLED] = {
      phone: this.form.phone
    }
    this.analyticsPulsar.action(AnalyticsAction.APPOINTMENT_PHONE_FILLED, analyticsData)
  }

  onPhoneChanged(phone: string) {
    this.form.phone = phone
  }

  onChangedPatientType() {
    const analyticsData: AnalyticsActionDataTypes[AnalyticsAction.APPOINTMENT_PATIENT_TYPE_CHANGED] = {
      patientType: this.form.type
    }
    this.analyticsPulsar.action(AnalyticsAction.APPOINTMENT_PATIENT_TYPE_CHANGED, analyticsData)
  }

  async onBookAppointment() {
    if (this.canBook) {
      const patient: Patient = {
        firstname: this.form.firstname!,
        lastname: this.form.lastname!,
        phone: this.form.phone!,
        type: this.form.type
      }
      this.isBookingAppointment = true
      try {
        await this.availabilityService.book(this.slot.uid, patient)
        this.toasterService.sendToast({
          type: "success",
          message: "Créneau réservé !"
        })
        this.appointmentBooked(this.slot, patient)
      } catch (error) {
        this.toasterService.sendToast({
          type: "error",
          message: "Impossible de réserver le créneau"
        })
        const analyticsData: AnalyticsActionDataTypes[AnalyticsAction.APPOINTMENT_BOOKED] = {
          date: this.slot.from,
          patient: `${patient.firstname} ${patient.lastname} (${patient.phone})`,
          success: false
        }
        this.analyticsPulsar.action(AnalyticsAction.APPOINTMENT_BOOKED, analyticsData)
      } finally {
        this.isBookingAppointment = false
      }
    }
  }
}
</script>

<style lang="scss">
.Appointment {
  &-header {
    display: flex;
    align-items: inherit;
    justify-content: space-between;
    padding-left: 0;
    padding-right: 0;
  }

  &-form {
    margin-top: 2rem;
    display: flex;
    flex-direction: column;
    gap: 1rem;
  }

  &-phone-digit {
    max-width: 10px;
  }
}
</style>

// client/src/components/app/appointment/appointment.component.ts
import {Component, EventEmitter, HostListener, Input, Output} from '@angular/core';
import {Button} from "primeng/button";
import {SlotPersisted} from "@shared/types/slot.interface";
import {NgIf} from "@angular/common";
import DateHelper from "@shared/helpers/date.helper";
import DateFormat from "@shared/types/date-format.enum";
import {CalendarModule} from "primeng/calendar";
import {DialogModule} from "primeng/dialog";
import {DividerModule} from "primeng/divider";
import {DropdownModule} from "primeng/dropdown";
import {Footer, Header} from "primeng/api";
import {InputTextModule} from "primeng/inputtext";
import {FormsModule, ReactiveFormsModule} from "@angular/forms";
import {Patient, PatientType} from "@shared/types/patient.interface";
import {InputOtpModule} from "primeng/inputotp";
import AvailabilityService from "../../../services/availability.service";
import {catchError, of, take} from "rxjs";
import {createPatientForm, PatientForm} from "../../../forms/patient.form";
import ToasterService from "../../../services/toaster.service";
import {PractitionerIconComponent} from "../../_design-system/practitioner-icon/practitioner-icon.component";
import {InputPhoneComponent} from "../../_design-system/input-phone/input-phone.component";
import {Practitioner} from "@shared/types/practitioner.enum";
import {MessagesModule} from "primeng/messages";
import AnalyticsPulsar from "../analytics.pulsar";
import {AnalyticsAction, AnalyticsActionDataTypes} from "@shared/types/analytics.types";

@Component({
  selector: 'op-appointment',
  standalone: true,
  imports: [
    Button,
    NgIf,
    CalendarModule,
    DialogModule,
    DividerModule,
    DropdownModule,
    Footer,
    Header,
    InputTextModule,
    FormsModule,
    InputOtpModule,
    ReactiveFormsModule,
    PractitionerIconComponent,
    InputPhoneComponent,
    MessagesModule
  ],
  templateUrl: './appointment.component.html',
  styleUrl: './appointment.component.scss'
})
export class AppointmentComponent {
  @Input({ required: true }) slot!: SlotPersisted
  @Output() cancelAppointment = new EventEmitter<void>()
  @Output() appointmentBooked = new EventEmitter<{
    slot: SlotPersisted,
    patient: Patient
  }>()

  @HostListener('document:keydown.escape', ['$event']) onKeydownHandler() {
    this.cancelAppointment.emit()
  }

  protected readonly DateHelper = DateHelper
  protected readonly DateFormat = DateFormat
  protected readonly Object = Object;

  isBookingAppointment = false
  form: PatientForm = createPatientForm()

  constructor(
    private readonly availabilityService: AvailabilityService,
    private readonly toastService: ToasterService,
    private readonly analyticsPulsar: AnalyticsPulsar
  ) {
  }

  get isSlotForChildrenOnly(): boolean {
    return (
      this.slot.practitioner === Practitioner.ROSE &&
      DateHelper.isWednesday(this.slot.from)
    )
  }

  get patientTypeOptions(): PatientType[] {
    if (this.isSlotForChildrenOnly) {
      return [
        PatientType.BABY,
        PatientType.CHILD
      ];
    }
    return Object.values(PatientType) as PatientType[]
  }

  get canBook(): boolean {
    return this.form.valid
  }

  onFocusOutLastname() {
    if (!this.form.controls.lastname.value?.length) {
      return
    }
    const analyticsData: AnalyticsActionDataTypes[AnalyticsAction.APPOINTMENT_LASTNAME_FILLED] = {
      lastname: this.form.controls.lastname.value!
    }
    this.analyticsPulsar.action(AnalyticsAction.APPOINTMENT_LASTNAME_FILLED, analyticsData)
  }

  onFocusOutFirstname() {
    if (!this.form.controls.firstname.value?.length) {
      return
    }
    const analyticsData: AnalyticsActionDataTypes[AnalyticsAction.APPOINTMENT_FIRSTNAME_FILLED] = {
      firstname: this.form.controls.firstname.value!
    }
    this.analyticsPulsar.action(AnalyticsAction.APPOINTMENT_FIRSTNAME_FILLED, analyticsData)
  }

  onFocusOutPhone() {
    if (!this.form.controls.phone.value?.length) {
      return
    }
    const analyticsData: AnalyticsActionDataTypes[AnalyticsAction.APPOINTMENT_PHONE_FILLED] = {
      phone: this.form.controls.phone.value!
    }
    this.analyticsPulsar.action(AnalyticsAction.APPOINTMENT_PHONE_FILLED, analyticsData)
  }

  onChangedPatientType() {
    const analyticsData: AnalyticsActionDataTypes[AnalyticsAction.APPOINTMENT_PATIENT_TYPE_CHANGED] = {
      patientType: this.form.controls.type.value!
    }
    this.analyticsPulsar.action(AnalyticsAction.APPOINTMENT_PATIENT_TYPE_CHANGED, analyticsData)
  }

  onBookAppointment() {
    if (!this.isBookingAppointment && this.form.valid) {
      const patient: Patient = {
        firstname: this.form.controls.firstname.value!,
        lastname: this.form.controls.lastname.value!,
        phone: this.form.controls.phone.value!,
        type: this.form.controls.type.value!
      }
      this.isBookingAppointment = true
      this.availabilityService.book(this.slot.uid, patient).pipe(
        take(1),
        catchError(() => {
          this.isBookingAppointment = false

          const analyticsData: AnalyticsActionDataTypes[AnalyticsAction.APPOINTMENT_BOOKED] = {
            date: this.slot.from,
            patient: `${patient.firstname} ${patient.lastname} (${patient.phone})`,
            success: false
          }
          this.analyticsPulsar.action(AnalyticsAction.APPOINTMENT_BOOKED, analyticsData)
          return of()
        })
      ).subscribe(() => {
        this.toastService.sendToast({
          severity: "success",
          summary: "Créneau réservé !"
        })
        this.isBookingAppointment = false
        this.appointmentBooked.emit({
          slot: this.slot,
          patient: patient
        })
      })
    }
  }
}

<p-dialog
  [modal]="true"
  [closable]="false"
  [visible]="true"
  [draggable]="false"
>
  <p-header>
    <div class="Appointment-header">
      <div class="p-dialog-title">
        Créneau du {{ DateHelper.format(slot.from, DateFormat.DATE_TIME) }}
      </div>
      <op-practitioner-icon
        [practitioner]="slot.practitioner"
        [width]="50"
      />
    </div>
  </p-header>
  <form class="Appointment-form" [formGroup]="form">
    <p class="Appointment-form-input">
      <label> Nom * </label>
      <input
        type="text"
        pInputText
        [autofocus]="false"
        [formControl]="form.controls.lastname"
        (focusout)="onFocusOutLastname()"
      />
    </p>
    <p-divider/>
    <p class="Appointment-form-input">
      <label> Prénom * </label>
      <input
        type="text"
        pInputText
        [autofocus]="false"
        [formControl]="form.controls.firstname"
        (focusout)="onFocusOutFirstname()"
      />
    </p>
    <p-divider/>
    <p class="Appointment-form-input">
      <label> Téléphone * </label>
      <op-input-phone
        (update)="onPhoneChanged($event)"
        (focusout)="onFocusOutPhone()"
      />
    </p>
    <p-divider/>
    <p class="Appointment-form-input">
      <label> Type de séance : </label>
      <p-dropdown
        appendTo="body"
        [autofocus]="false"
        [options]="patientTypeOptions"
        [formControl]="form.controls.type"
        (onChange)="onChangedPatientType()"
      />
    </p>
  </form>
  <p-footer>
    <p-messages
      *ngIf="isSlotForChildrenOnly"
      [value]="[{
        'severity': 'warn',
        'summary': 'Les créneaux du mercredi sont réservés aux bébés/enfants'
      }]"
      [enableService]="false"
      [closable]="false"
    />
    <p-button (onClick)="cancelAppointment.emit()">Annuler</p-button>
    <p-button
      severity="warning"
      (onClick)="onBookAppointment()"
      [disabled]="!canBook"
      [loading]="isBookingAppointment"
    >
      Réserver le créneau
    </p-button>
  </p-footer>
</p-dialog>
