// client/src/components/app/infos/infos.component.ts
import {Component, EventEmitter, HostListener, Output} from "@angular/core";
import {DialogModule} from "primeng/dialog";
import {Button} from "primeng/button";

@Component({
  selector: 'op-infos',
  standalone: true,
  imports: [
    DialogModule,
    Button
  ],
  templateUrl: './infos.component.html',
  styleUrl: './infos.component.scss'
})
export class InfosComponent {
  @Output() closeIt = new EventEmitter<void>();
  @HostListener('document:keydown.escape', ['$event']) onKeydownHandler() {
    this.closeIt.emit()
  }
}

<p-dialog
  [modal]="true"
  [visible]="true"
  [closable]="false"
>
  <p-header>
    Infos pratiques
  </p-header>
  <div class="Infos">
    <div class="Infos-item">
      <span class="pi pi-map-marker mr-6"></span>
      <a href="https://maps.app.goo.gl/E6vYw1tQbJ8j22Ye6" target="_blank">Village anglais rue Georges Ohnet, 77340 Pontault-Combault</a>
    </div>
    <div class="Infos-item">
      <span class="pi pi-phone mr-6"></span>
      <a href="tel://+33695084023">06 95 08 40 23</a>
    </div>
    <div class="Infos-item">
      <span class="pi pi-euro mr-6"></span>
      <span>Paiement par chèque ou espèces — pas de CB</span>
    </div>
    <div class="Infos-item">
      <span class="pi pi-thumbs-up mr-6"></span>
      <span>Conventionné pour remboursement mutuelle</span>
    </div>
    <div class="Infos-item">
      <span class="pi pi-car mr-6"></span>
      <span>Parking et services à proximité (poissonnerie, boulangerie, pharmacie, ...)</span>
    </div>
  </div>
  <p-footer>
    <p-button (onClick)="closeIt.emit()">Ok</p-button>
  </p-footer>
</p-dialog>

// client/src/components/app/Infos.vue
<template>
  <v-card>
    <v-card-title>
      Infos pratiques
    </v-card-title>
    <v-card-text>
      <div class="Infos">
        <div class="Infos-item">
          <Location/>
        </div>
        <div class="Infos-item">
          <Phone :icon-inlined="false"/>
        </div>
        <div class="Infos-item">
          <v-icon start icon="mdi-currency-eur"/>
          <span>Paiement par chèque ou espèces — pas de CB</span>
        </div>
        <div class="Infos-item">
          <v-icon start icon="mdi-thumb-up"/>
          <span>Conventionné pour remboursement mutuelle</span>
        </div>
        <div class="Infos-item">
          <v-icon start icon="mdi-car"/>
          <span>Parking et services à proximité (pharmacie, poissonnerie, boulangerie, ...)</span>
        </div>
      </div>
    </v-card-text>
    <v-card-actions>
      <Button
        :active="true"
        label="Ok" @click="closeIt()"
      />
    </v-card-actions>
  </v-card>
</template>

<script lang="ts">
import {Component, Emit, Vue} from "vue-facing-decorator";
import Phone from "@/components/_design-system/Phone.vue";
import Location from "@/components/_design-system/Location.vue";
import Button from "@/components/_design-system/Button.vue";

@Component({
  components: {Button, Location, Phone}
})
export default class Infos extends Vue {
  @Emit()
  closeIt() {
  }
}
</script>

<style lang="scss">
.Infos {
  display: flex;
  flex-direction: column;
  gap: 1.5rem;

  .pi {
    margin-right: 1rem;
  }

  &-item {
    display: flex;
    align-items: center;
  }
}
</style>
