// client2/src/components/admin/AvailabilityEdit.vue
<template>
  <v-card
    class="pa-6"
    max-width="100vw"
    width="550px"
  >
    <v-card-title>Modifier un créneau</v-card-title>

    <v-card-text>
      <form class="Availability-edit-form">
        <InputDate
          v-model="form.from"
          label="De :"
        />
        <InputDate
          v-model="form.to"
          label="À :"
        />
        <template v-if="practitioner === Practitioner.ROSE">
          <v-select
            v-model="form.practitioner"
            variant="outlined"
            label="Pour"
            rounded
            :autofocus="false"
            :items="Object.values(Practitioner)"
          />
        </template>
        <div class="d-flex">
          <v-spacer/>
          <v-switch
            v-model="form.hasPatient"
            label="Patient"
            color="primary"
            @change="onHasPatientChanged()"
          />
        </div>
        <template v-if="form.hasPatient && form.patient">
          <template v-if="form.bookedAt">
            <InputDate
              v-model="form.bookedAt"
              label="Créneau pris le"
              disabled
            />
          </template>
          <v-text-field
            v-model="form.patient!.lastname"
            variant="outlined"
            label="Nom"
            rounded
          />
          <v-text-field
            v-model="form.patient!.firstname"
            variant="outlined"
            label="Prénom"
            rounded
          />
          <InputPhone
            :initial-value="slot.patient?.phone"
            @update="onPhoneChanged($event)"
          />
          <v-select
            v-model="form.patient!.type"
            variant="outlined"
            label="Type de séance"
            :autofocus="false"
            :items="Object.values(PatientType)"
            rounded
          />
        </template>
      </form>
    </v-card-text>

    <v-card-actions :class="{ 'justify-space-evenly': isMobile }">
      <Button
        size="large"
        :label="isMobile ? '' : 'Annuler'"
        :icon="isMobile ? 'mdi-undo' : null"
        :active="true"
        @click="cancelled()"
      />
      <Button
        size="large"
        color="danger"
        :label="isMobile ? '' : 'Supprimer'"
        :icon="isMobile ? 'mdi-trash-can' : null"
        :active="true"
        :loading="isEditingSlot"
        @click="onRemoveSlot()"
      />
      <Button
        size="large"
        color="success"
        :label="isMobile ? '' : 'Modifier'"
        :icon="isMobile ? 'mdi-check-bold' : null"
        :active="true"
        :loading="isEditingSlot"
        @click="onEditSlot()"
      />
    </v-card-actions>
  </v-card>

  <v-dialog v-model="isRemovingSlot" :fullscreen="isMobile">
    <v-card position="absolute" :location="'center center'">
      <v-card-title>
        Confirmer la suppression du créneau ?
      </v-card-title>
      <v-card-actions>
        <Button
          label="Annuler"
          size="large"
          :active="true"
          @click="onCancelRemoveSlot()"
        />
        <Button
          label="Supprimer"
          color="secondary"
          size="large"
          :active="true"
          :loading="isEditingSlot"
          @click="onConfirmRemoveSlot()"
        />
      </v-card-actions>
    </v-card>
  </v-dialog>
</template>

<script lang="ts">
import {Component, Emit, Prop, Vue, Watch} from "vue-facing-decorator";
import {Practitioner} from "@shared/types/practitioner.enum";
import DateFormat from "@shared/types/date-format.enum";
import {PatientType} from "@shared/types/patient.interface";
import {Container} from "typedi";
import AvailabilityHttpService from "@/services/http/availability.http-service";
import ToasterService from "@/services/snackbar/toaster.service";
import type {SlotPersisted} from "@shared/types/slot.interface";
import {createSlotForm} from "@/forms/slot.form";
import InputPhone from "@/components/_design-system/InputPhone.vue";
import InputDate from "@/components/_design-system/InputDate.vue";
import Button from "@/components/_design-system/Button.vue";

@Component({
  components: {Button, InputDate, InputPhone}
})
export default class AvailabilityEdit extends Vue {
  @Prop({ required: true }) practitioner!: Practitioner
  @Prop({ required: true }) slot!: SlotPersisted

  @Emit() slotEdited() {
  }
  @Emit() slotRemoved() {
  }
  @Emit() cancelled() {
  }

  private readonly availabilityService = Container.get(AvailabilityHttpService)
  private readonly toasterService = Container.get(ToasterService)

  readonly Practitioner = Practitioner
  readonly DateFormat = DateFormat
  readonly Object = Object
  readonly PatientType = PatientType

  isEditingSlot = false
  isRemovingSlot = false
  form = createSlotForm()

  get isMobile(): boolean {
    return document.body.clientWidth < 800
  }

  @Watch('slot', { immediate: true })
  onSlotChanged() {
    if (!this.slot) {
      return
    }
    this.form = {
      from: new Date(this.slot.from),
      to: new Date(this.slot.to),
      practitioner: this.slot.practitioner,
      bookedAt: this.slot.bookedAt ? new Date(this.slot.bookedAt) : undefined,
      hasPatient: this.slot.hasPatient,
      patient: null
    }
    if (this.slot.patient) {
      this.form.patient = {
        ...this.slot.patient
      }
    }
  }

  onPhoneChanged(phone: string) {
    if (!this.form.patient) {
      return
    }
    if (this.form.patient?.phone) {
      this.form.patient.phone = phone
    }
  }

  onHasPatientChanged() {
    if (this.form.hasPatient) {
      this.form.patient = this.slot.patient
        ? {...this.slot.patient}
        : {
          firstname: "",
          lastname: "",
          phone: "0",
          type: PatientType.ADULT
        }
    }
  }

  onRemoveSlot() {
    if (this.slot.hasPatient) {
      this.isRemovingSlot = true
    } else {
      this.onConfirmRemoveSlot()
    }
  }

  async onEditSlot() {
    const newSlotFrom = new Date(this.slot.from)
    const newSlotTo = new Date(this.slot.to)
    const sendNotification = !this.slot.hasPatient && !!this.form.hasPatient
    newSlotFrom.setHours(this.form.from.getHours())
    newSlotFrom.setMinutes(this.form.from.getMinutes())
    newSlotTo.setHours(this.form.to.getHours())
    newSlotTo.setMinutes(this.form.to.getMinutes())

    try {
      await this.availabilityService.edit({
        uid: this.slot.uid,
        from: newSlotFrom.toISOString(),
        to: newSlotTo.toISOString(),
        practitioner: this.form.practitioner,
        bookedAt: this.form.bookedAt?.toISOString(),
        hasPatient: !!this.form.hasPatient,
        patient: !this.form.hasPatient || !this.form.patient ? null : {
          firstname: this.form.patient.firstname!,
          lastname: this.form.patient.lastname!,
          phone: this.form.patient.phone!,
          type: this.form.patient.type!
        }
      }, sendNotification)
      this.toasterService.sendToast({
        type: "success",
        message: "Créneau modifié"
      })
      this.slotEdited();
    } catch {
      this.toasterService.sendToast({
        type: "error",
        message: "Impossible de modifier le créneau",
      })
    } finally {
      this.isEditingSlot = false
    }
  }

  onCancelRemoveSlot() {
    this.isRemovingSlot = false
  }

  async onConfirmRemoveSlot() {
    this.isEditingSlot = true

    try {
      await this.availabilityService.remove(this.slot)
      this.toasterService.sendToast({
        type: "success",
        message: "Créneau supprimé"
      })
      this.slotRemoved();
    } catch {
      this.toasterService.sendToast({
        type: "error",
        message: "Impossible de supprimer le créneau",
      })
    } finally {
      this.isEditingSlot = false
    }
  }
}
</script>

<style lang="scss">
.Availability-edit {
  &-form {
    &-input {
      display: flex;
      align-items: center;
      justify-content: space-between;
      @media (max-width: 1100px) {
        flex-direction: column;
        align-items: inherit;
        gap: .5rem;
      }
    }
  }
}
</style>

// client/src/components/admin/availability-edit/availability-edit.component.ts
import {Component, EventEmitter, HostListener, Input, OnChanges, Output, SimpleChanges} from "@angular/core";
import {Practitioner} from "@shared/types/practitioner.enum";
import {Footer} from "primeng/api";
import {Button} from "primeng/button";
import {CalendarModule} from "primeng/calendar";
import {DividerModule} from "primeng/divider";
import {DialogModule} from "primeng/dialog";
import {FormsModule, ReactiveFormsModule} from "@angular/forms";
import {DropdownModule} from "primeng/dropdown";
import {PaginatorModule} from "primeng/paginator";
import DateFormat from "@shared/types/date-format.enum";
import {take} from "rxjs";
import AvailabilityService from "../../../services/availability.service";
import {NgIf} from "@angular/common";
import {SlotPersisted} from "@shared/types/slot.interface";
import {PatientType} from "@shared/types/patient.interface";
import ToasterService from "../../../services/toaster.service";
import {InputOtpModule} from "primeng/inputotp";
import {InputTextModule} from "primeng/inputtext";
import {InputSwitchModule} from "primeng/inputswitch";
import {InputPhoneComponent} from "../../_design-system/input-phone/input-phone.component";
import {createSlotForm} from "../../../forms/slot.form";

@Component({
  selector: 'op-availability-edit',
  standalone: true,
  imports: [
    Footer,
    Button,
    Button,
    Button,
    CalendarModule,
    DividerModule,
    DialogModule,
    FormsModule,
    DropdownModule,
    PaginatorModule,
    NgIf,
    InputOtpModule,
    InputTextModule,
    InputSwitchModule,
    InputPhoneComponent,
    ReactiveFormsModule
  ],
  templateUrl: './availability-edit.component.html',
  styleUrl: './availability-edit.component.scss'
})
export class AvailabilityEditComponent implements OnChanges {
  @Input({ required: true }) slot!: SlotPersisted
  @Output() slotEdited = new EventEmitter<void>()
  @Output() slotRemoved = new EventEmitter<void>()
  @Output() cancelled = new EventEmitter<void>()

  @HostListener('document:keydown.escape', ['$event']) onKeydownHandler() {
    if (this.isRemovingSlot) {
      this.onCancelRemoveSlot()
    } else {
      this.cancelled.emit()
    }
  }

  protected readonly Practitioner = Practitioner
  protected readonly DateFormat = DateFormat;
  protected readonly Object = Object
  protected readonly PatientType = PatientType;

  isEditingSlot = false
  isRemovingSlot = false
  form = createSlotForm()

  constructor(
    private readonly availabilityService: AvailabilityService,
    private readonly toastService: ToasterService
  ) {
  }

  ngOnChanges(changes: SimpleChanges) {
    const slotChanges = changes['slot']
    if (slotChanges) {
      const slot = slotChanges.currentValue as SlotPersisted
      this.form.patchValue({
        from: new Date(slot.from),
        to: new Date(slot.to),
        practitioner: slot.practitioner,
        bookedAt: slot.bookedAt ? new Date(slot.bookedAt) : undefined,
        hasPatient: slot.hasPatient,
      })
      if (slot.patient) {
        this.form.controls.patient.patchValue({
          ...slot.patient
        })
      }
    }
  }

  onHasPatientChanged() {
    if (this.form.controls.hasPatient.value) {
      this.form.controls.patient.patchValue(this.slot.patient ?? {
        firstname: "",
        lastname: "",
        phone: "0",
        type: PatientType.ADULT
      })
    }
  }

  onRemoveSlot() {
    if (this.slot.hasPatient) {
      this.isRemovingSlot = true
    } else {
      this.onConfirmRemoveSlot()
    }
  }

  onEditSlot() {
    const newSlotFrom = new Date(this.slot.from)
    const newSlotTo = new Date(this.slot.to)
    const sendNotification = !this.slot.hasPatient && !!this.form.controls.hasPatient.value
    newSlotFrom.setHours(this.form.controls.from.value!.getHours())
    newSlotFrom.setMinutes(this.form.controls.from.value!.getMinutes())
    newSlotTo.setHours(this.form.controls.to.value!.getHours())
    newSlotTo.setMinutes(this.form.controls.to.value!.getMinutes())
    this.availabilityService.edit({
      uid: this.slot.uid,
      from: newSlotFrom.toISOString(),
      to: newSlotTo.toISOString(),
      practitioner: this.form.controls.practitioner.value!,
      bookedAt: this.form.controls.bookedAt.value?.toISOString(),
      hasPatient: !!this.form.controls.hasPatient.value,
      patient: !this.form.controls.hasPatient.value ? null : {
        firstname: this.form.controls.patient.controls.firstname.value!,
        lastname: this.form.controls.patient.controls.lastname.value!,
        phone: this.form.controls.patient.controls.phone.value!,
        type: this.form.controls.patient.controls.type.value!
      }
    }, sendNotification).pipe(take(1)).subscribe(() => {
      this.toastService.sendToast({
        severity: "success",
        summary: "Créneau modifié"
      })
      this.isEditingSlot = false
      this.slotEdited.emit();
    })
  }

  onCancelRemoveSlot() {
    this.isRemovingSlot = false
  }

  onConfirmRemoveSlot() {
    this.isEditingSlot = true
    this.availabilityService.remove(this.slot).pipe(take(1)).subscribe(() => {
      this.toastService.sendToast({
        severity: "success",
        summary: "Créneau supprimé"
      })
      this.isEditingSlot = false
      this.slotRemoved.emit();
    })
  }
}

<p-dialog
  [modal]="true"
  [closable]="false"
  [visible]="true"
>
  <p-header>
    Modifier un créneau
  </p-header>
  <form class="Availability-edit-form" [formGroup]="form">
    <input type="hidden"/>
    <p class="Availability-edit-form-input">
      <label> De : </label>
      <p-calendar
        appendTo="body"
        [formControl]="form.controls.from"
        [timeOnly]="true"
      />
    </p>
    <p class="Availability-edit-form-input">
      <label> À : </label>
      <p-calendar
        appendTo="body"
        [formControl]="form.controls.to"
        [timeOnly]="true"
        [showOnFocus]="false"
      />
    </p>
    <p class="Availability-edit-form-input">
      <label> Pour : </label>
      <p-dropdown
        appendTo="body"
        [options]="Object.values(Practitioner)"
        [formControl]="form.controls.practitioner"
      />
    </p>
    <p-divider/>
    <p class="Availability-edit-form-input mb-24" style="flex-direction: row">
      <label> Patient : </label>
      <p-inputSwitch
        [formControl]="form.controls.hasPatient"
        (onChange)="onHasPatientChanged()"
      />
    </p>
    <ng-container *ngIf="form.controls.hasPatient.value" [formGroup]="form.controls.patient">
      <p *ngIf="form.controls.bookedAt.value" class="Availability-edit-form-input">
        <label> Créneau pris le </label>
        <p-calendar
          appendTo="body"
          [dateFormat]="DateFormat.DATE_PRIME"
          [formControl]="form.controls.bookedAt"
          [showTime]="true"
          [disabled]="true"
        />
      </p>
      <p class="Availability-edit-form-input">
        <label> Nom </label>
        <input
          type="text"
          pInputText
          [formControl]="form.controls.patient.controls.lastname"
        />
      </p>
      <p class="Availability-edit-form-input">
        <label> Prénom </label>
        <input
          type="text"
          pInputText
          [formControl]="form.controls.patient.controls.firstname"
        />
      </p>
      <p class="Availability-edit-form-input">
        <label> Téléphone </label>
        <op-input-phone
          [initialValue]="slot.patient?.phone"
          (update)="onPhoneChanged($event)"
        />
      </p>
      <p class="Availability-edit-form-input">
        <label> Type de séance : </label>
        <p-dropdown
          appendTo="body"
          [options]="Object.values(PatientType)"
          [formControl]="form.controls.patient.controls.type"
        />
      </p>
    </ng-container>
  </form>
  <p-footer>
    <p-button (onClick)="cancelled.emit()">Annuler</p-button>
    <p-button (onClick)="onRemoveSlot()" severity="danger" [loading]="isEditingSlot">Supprimer</p-button>
    <p-button (onClick)="onEditSlot()" severity="warning" [loading]="isEditingSlot">Modifier</p-button>
  </p-footer>
</p-dialog>

<p-dialog [modal]="true" [visible]="isRemovingSlot">
  <p-header>
    Confirmer la suppression du créneau ?
  </p-header>
  <p-footer>
    <p-button (onClick)="onCancelRemoveSlot()">Annuler</p-button>
    <p-button (onClick)="onConfirmRemoveSlot()" severity="danger" [loading]="isEditingSlot">Supprimer</p-button>
  </p-footer>
</p-dialog>
