// client2/src/components/app/Timeline.vue
<template>
  <v-timeline
    align="start"
    side="end"
    truncate-line="both"
    class="Timeline"
    :value="isLoading ? loaders : availabilities"
  >
    <v-timeline-item
      v-for="availability of isLoading ? loaders : availabilities"
      dot-color="primary"
      size="small"
    >
      <!-- Date -->
      <template v-slot:opposite>
        <v-skeleton-loader
          v-if="isLoading || availability === null"
          style="width: 141px; height: 42px; display: flex; justify-content: end; border-radius: 1rem;"
        />
        <Button
          v-else
          class="unclickable"
          size="large"
          :outlined="true"
          :label="DateHelper.format(availability.date, DateFormat.FULL_DATE)"
        />
      </template>

      <!-- Practitioner Icon -->
<!--      <template v-slot:icon>-->
<!--        <div class="Timeline-separator">-->
<!--          <Hexagon :width="20" color="#2196F3"/>-->
<!--        </div>-->
<!--      </template>-->

      <!-- Slots list -->
      <template v-slot:default>
        <div class="Timeline-slots">
          <v-skeleton-loader
            v-if="isLoading || availability === null"
            v-for="_ of loadingSlots"
            style="width: 104px; height: 46px; display: flex; justify-content: end; border-radius: 1rem;"
          />
          <template v-else>
            <Button
              v-for="slot of availability.slots"
              size="large"
              :active="true"
              :color="slot.practitioner !== Practitioner.ROSE ? 'anais' : 'rose'"
              :label="DateHelper.format(availability.date, DateFormat.TIME)"
              @click="slotClicked(slot)"
            >
              <div class="Timeline-slots-slot font-weight-bold">
                <span class="mr-2">{{ DateHelper.format(slot.from, DateFormat.TIME) }}</span>
                <IconPractitioner :practitioner="slot.practitioner"/>
              </div>
            </Button>
          </template>
        </div>
      </template>
    </v-timeline-item>
  </v-timeline>
</template>

<script lang="ts">
import {Component, Emit, Prop, Vue} from "vue-facing-decorator";
import IconPractitioner from "@/components/_design-system/IconPractitioner.vue";
import Hexagon from "@/components/_design-system/Hexagon.vue";
import type {SlotPersisted} from "@shared/types/slot.interface";
import type {Availability} from "@shared/types/availability.interface";
import DateHelper from "../../../../shared/helpers/date.helper";
import DateFormat from "../../../../shared/types/date-format.enum";
import {Practitioner} from "@shared/types/practitioner.enum";
import Button from "@/components/_design-system/Button.vue";

@Component({
  components: {Button, Hexagon, IconPractitioner}
})
export default class Timeline extends Vue {
  readonly Practitioner = Practitioner
  readonly DateFormat = DateFormat
  readonly DateHelper = DateHelper

  @Prop({ required: true }) isLoading!: boolean
  @Prop() availabilities!: Availability[]

  loaders = new Array<null>(5).fill(null)
  loadingSlots = new Array<null>(5).fill(null)

  @Emit()
  slotClicked(slot: SlotPersisted) {
    return slot
  }
}
</script>

<style lang="scss">
.Timeline {
  &-slots {
    display: flex;
    flex-wrap: wrap;
    gap: 1rem;
    &-slot {
      display: flex;
      align-items: center;
      justify-content: space-between;
    }
  }
  &-separator {
    position: relative;
    transform: translateY(25%);
  }
}

:host ::ng-deep {
  p-timeline {
    .p-timeline-event {
      margin-top: 1rem;
      margin-bottom: 1rem;
    }
    .p-timeline-event-connector {
      transform: translateY(1.25rem);
    }
    .p-timeline-event-opposite {
      *:first-letter {
        text-transform: uppercase;
      }
    }
  }
}
</style>

// client/src/components/app/timeline/timeline.component.ts
import {Component, EventEmitter, Input, Output} from '@angular/core';
import {NgClass, NgForOf, NgIf, NgStyle} from "@angular/common";
import {TimelineModule} from "primeng/timeline";
import {HexagonComponent} from "../../_design-system/hexagon/hexagon.component";
import {Availability} from "@shared/types/availability.interface";
import {Button} from "primeng/button";
import {Practitioner} from "@shared/types/practitioner.enum";
import DateHelper from "@shared/helpers/date.helper";
import DateFormat from "@shared/types/date-format.enum";
import {SlotPersisted} from "@shared/types/slot.interface";
import {PractitionerIconComponent} from "../../_design-system/practitioner-icon/practitioner-icon.component";
import {SkeletonModule} from "primeng/skeleton";

@Component({
  selector: 'op-timeline',
  standalone: true,
  imports: [
    NgStyle,
    TimelineModule,
    HexagonComponent,
    Button,
    NgForOf,
    NgIf,
    NgClass,
    PractitionerIconComponent,
    SkeletonModule
  ],
  templateUrl: './timeline.component.html',
  styleUrl: './timeline.component.scss'
})
export class TimelineComponent {
  @Input({ required: true }) isLoading!: boolean
  @Input() availabilities!: Availability[]
  @Output() slotClicked = new EventEmitter<SlotPersisted>()

  protected readonly Practitioner = Practitioner
  protected readonly DateHelper = DateHelper
  protected readonly DateFormat = DateFormat

  loaders = new Array<null>(5).fill(null)
  loadingSlots = new Array<null>(5).fill(null)

  onSlotClick(slot: SlotPersisted) {
    this.slotClicked.emit(slot)
  }
}

<p-timeline
  class="Timeline"
  [value]="isLoading ? loaders : availabilities"
  [style]="{
    display: 'flex',
    alignItems: 'center',
  }"
>
  <ng-template pTemplate="marker">
    <div class="Timeline-separator">
      <op-hexagon [width]="20" color="#2196F3"/>
    </div>
  </ng-template>
  <ng-template pTemplate="opposite" let-availability>
    <ng-container *ngIf="isLoading || availability === null">
      <p-skeleton
        [ngStyle]="{ display: 'flex', justifyContent: 'end' }"
        width="141px"
        height="42px"
        borderRadius="1rem"
      />
    </ng-container>
    <ng-container *ngIf="!isLoading && availability">
      <p-button styleClass="unclickable" outlined>
        {{ DateHelper.format(availability.date, DateFormat.FULL_DATE) }}
      </p-button>
    </ng-container>
  </ng-template>
  <ng-template pTemplate="content" let-availability>
    <div class="Timeline-slots">
      <ng-container *ngIf="isLoading || availability === null">
        <p-skeleton *ngFor="let loadingSlot of loadingSlots" width="104px" height="46px" borderRadius="1rem"/>
      </ng-container>
      <ng-container *ngIf="!isLoading && availability">
        <div
          class="p-button p-button-large"
          *ngFor="let slot of availability.slots"
          [ngClass]="{
          'p-button-primary': slot.practitioner === Practitioner.ROSE,
          'p-button-help': slot.practitioner !== Practitioner.ROSE
        }"
          (click)="onSlotClick(slot)"
        >
          <div class="Timeline-slots-slot">
            <span class="mr-12">{{ DateHelper.format(slot.from, DateFormat.TIME) }}</span>
            <op-practitioner-icon [practitioner]="slot.practitioner"/>
          </div>
        </div>
      </ng-container>
    </div>
  </ng-template>
</p-timeline>
