// client/src/components/admin/availability-list/availability-list.component.ts
import {Component, ElementRef, Input, OnInit, ViewChild} from "@angular/core";
import {catchError, take} from "rxjs";
import {CalendarModule} from "primeng/calendar";
import {NgClass, NgForOf, NgIf, NgStyle, NgTemplateOutlet} from "@angular/common";
import {Availability} from "@shared/types/availability.interface";
import AvailabilityService from "../../../services/availability.service";
import {FormsModule} from "@angular/forms";
import DateFormat from "@shared/types/date-format.enum";
import DateHelper from "@shared/helpers/date.helper";
import {TableModule} from "primeng/table";
import {SlotPersisted} from "@shared/types/slot.interface";
import {Practitioner} from "@shared/types/practitioner.enum";
import {AvailabilityEditComponent} from "../availability-edit/availability-edit.component";
import {HexagonComponent} from "../../_design-system/hexagon/hexagon.component";
import {AvailabilityAddComponent} from "../availability-add/availability-add.component";
import {PractitionerIconComponent} from "../../_design-system/practitioner-icon/practitioner-icon.component";
import {ProgressSpinnerModule} from "primeng/progressspinner";
import {DEFAULT_SLOT_DURATION} from "../../../utils/constants";

@Component({
  selector: 'op-availability-list',
  standalone: true,
  imports: [
    FormsModule,
    NgForOf,
    CalendarModule,
    CalendarModule,
    NgForOf,
    FormsModule,
    TableModule,
    NgIf,
    AvailabilityEditComponent,
    HexagonComponent,
    NgClass,
    AvailabilityAddComponent,
    NgTemplateOutlet,
    PractitionerIconComponent,
    ProgressSpinnerModule,
    NgStyle
  ],
  templateUrl: './availability-list.component.html',
  styleUrl: './availability-list.component.scss'
})
export class AvailabilityListComponent implements OnInit {
  @Input({ required: true }) practitioner!: Practitioner
  @ViewChild("gridDesktopComponent") gridDesktopComponent!: ElementRef
  @ViewChild("gridMobileComponent") gridMobileComponent!: ElementRef

  protected readonly DateFormat = DateFormat;
  protected readonly DateHelper = DateHelper;
  protected readonly Practitioner = Practitioner;
  protected readonly DEFAULT_SLOT_DURATION = DEFAULT_SLOT_DURATION;

  baseDateForSearch = new Date()
  availabilities: Availability[] = []
  isLoadingAvailabilities = false
  editingSlot: SlotPersisted | null = null
  addingAvailability = false
  baseDatesForAddingAvailability: [Date | null, Date | null] = [null, null]

  constructor(
    private readonly availabilityService: AvailabilityService
  ) {
  }

  get isMobile(): boolean {
    return document.body.clientWidth < 800
  }

  get hours(): number[] {
    return  new Array<number>(24).fill(0).map((h, index) => index)
  }

  get week(): Date[] {
    return DateHelper.getWeekFromDate(this.baseDateForSearch)
  }

  get availabilitiesPerWeekDay(): { [dayOfWeek: number]: SlotPersisted[] } {
    const availabilities: { [dayOfWeek: number]: SlotPersisted[] } = {}
    this.week.forEach((dayOfWeek) => {
      availabilities[dayOfWeek.getDay()] = []
    })
    this.availabilities.forEach((availability) => {
      const dayOfWeek = new Date(availability.date).getDay()
      availabilities[dayOfWeek].push(...availability.slots.sort((s1, s2) => s1.from < s2.from ? -1 : 1))
    })
    return availabilities
  }

  ngOnInit() {
    this.loadAvailabilities()
  }

  onAddAvailability(fromDate: string | null, toDate: string | null) {
    if (fromDate) {
      this.baseDatesForAddingAvailability[0] = new Date(fromDate)
    } else {
      this.baseDatesForAddingAvailability[0] = null
    }
    if (toDate) {
      this.baseDatesForAddingAvailability[1] = new Date(toDate)
    } else {
      this.baseDatesForAddingAvailability[1] = null
    }
    this.addingAvailability = true
  }

  onEditSlot(slot: SlotPersisted) {
    this.editingSlot = slot
  }

  onCancelEdit() {
    this.editingSlot = null
  }

  onSlotEditedOrRemoved() {
    this.editingSlot = null
    this.loadAvailabilities()
  }

  onCancelAdd() {
    this.addingAvailability = false
  }

  onAvailabilityAdded() {
    this.addingAvailability = false
    this.loadAvailabilities()
  }

  onPreviousWeek() {
    const newDate = new Date(this.baseDateForSearch)
    newDate.setDate(newDate.getDate() - 7)
    this.baseDateForSearch = newDate
    this.loadAvailabilities()
    this.focusGrid()
  }

  onCurrentWeek() {
    this.baseDateForSearch = new Date()
    this.loadAvailabilities()
    this.focusGrid()
  }

  onNextWeek() {
    const newDate = new Date(this.baseDateForSearch)
    newDate.setDate(newDate.getDate() + 7)
    this.baseDateForSearch = newDate
    this.loadAvailabilities()
    this.focusGrid()
  }

  loadAvailabilities() {
    if (this.isLoadingAvailabilities) {
      return
    }
    this.isLoadingAvailabilities = true
    const from = this.week[0]
    const to = new Date(from)
    to.setDate(to.getDate() + 7)
    this.availabilities = []
    this.availabilityService
      .list(from, to)
      .pipe(
        take(1),
        catchError(() => {
          this.isLoadingAvailabilities = false
          return []
        })
      )
      .subscribe((availabilities) => {
        this.isLoadingAvailabilities = false
        this.availabilities = availabilities
        this.scrollToMidday()
      })
  }

  getSlotsFromDay(dayOfWeek: Date): SlotPersisted[] {
    return this.availabilitiesPerWeekDay[dayOfWeek.getDay()]
  }

  getDefaultSlotDate(dayOfWeek: Date): string {
    const date = new Date(dayOfWeek)
    date.setHours(14, 0, 0, 0)
    return date.toISOString()
  }

  getCreationSlotsDataFor(
    base: Date,
    from: string | null,
    to: string | null
  ): Array<{from: string, to: string, diff: number }> {
    const start: Date = from ? new Date(from) : new Date(base)
    const end = to ? new Date(to) : new Date(base)
    const creationSlotsData: Array<{
      from: string
      to: string
      diff: number
    }> = []

    if (!from) {
      start.setHours(8, 0, 0, 0)
    }
    if (!to) {
      end.setHours(23, 0, 0, 0)
    }

    if (!to) {
      for (let time = start.getTime(); time < end.getTime(); time += DEFAULT_SLOT_DURATION * 60 * 1000) {
        const creationFromTime = time
        const creationToTime = Math.min(
          time + DEFAULT_SLOT_DURATION * 60 * 1000,
          end.getTime()
        )
        creationSlotsData.push({
          from: new Date(creationFromTime).toISOString(),
          to: new Date(creationToTime).toISOString(),
          diff: Math.floor((creationToTime - creationFromTime) / (60 * 1000))
        })
      }
      return creationSlotsData
    }

    for (let time = end.getTime(); time > start.getTime(); time -= DEFAULT_SLOT_DURATION * 60 * 1000) {
      const creationToTime = time
      const creationFromTime = Math.max(
        time - DEFAULT_SLOT_DURATION * 60 * 1000,
        start.getTime()
      )
      creationSlotsData.push({
        from: new Date(creationFromTime).toISOString(),
        to: new Date(creationToTime).toISOString(),
        diff: Math.floor((creationToTime - creationFromTime) / (60 * 1000))
      })
    }
    return creationSlotsData
  }

  focusGrid() {
    if (this.isMobile) {
      this.gridMobileComponent.nativeElement.focus()
    } else {
      this.gridDesktopComponent.nativeElement.focus()
    }
  }

  scrollToMidday() {
    if (!this.isMobile) {
      this.gridDesktopComponent.nativeElement.parentElement.scrollTo(0, 60 * 11)
    }
  }

  getCssClassesForSlot(from: string, to: string): string {
    const startInMinutes = DateHelper.getTimeInMinutes(from)
    const durationInMinutes = DateHelper.getDifferenceOfTimeInMinutes(from, to)
    return `AvailabilityList-slot-top-${startInMinutes} AvailabilityList-slot-height-${durationInMinutes}`
  }

  getCssClassesForEmptyDay() {
    return `AvailabilityList-slot-top-0 AvailabilityList-slot-height-${24 * 60}`
  }
}

<div class="AvailabilityList-filter">
  <p-button (onClick)="onPreviousWeek()" icon="pi pi-arrow-left"/>
  <p-button (onClick)="onCurrentWeek()">
    Semaine du {{ DateHelper.format(week[0], DateFormat.SHORT_DATE_API) }}
  </p-button>
  <p-button (onClick)="onNextWeek()" icon="pi pi-arrow-right"/>
</div>


<!-- //////////////////////////////////////////////////////////////////////////////////////////////////// -->
<!-- ////////////////////////////////////////// FOR MOBILE VIEW  //////////////////////////////////////// -->
<!-- //////////////////////////////////////////////////////////////////////////////////////////////////// -->
<div
  *ngIf="isMobile"
  class="AvailabilityListMobile-container"
>
  <div class="AvailabilityListMobile-calendar">
    <div class="AvailabilityListMobile-calendar-days">
      <div *ngFor="let dayOfWeek of week" class="AvailabilityListMobile-calendar-days-item">
        {{ DateHelper.format(dayOfWeek, DateFormat.MEDIUM_DATE) }}
      </div>
      <div class="AvailabilityListMobile-calendar-days-scrollbar"></div>
    </div>

    <div class="AvailabilityListMobile-calendar-week">
      <div class="AvailabilityListMobile-calendar-week-container" #gridMobileComponent tabindex="0">
        <div *ngFor="let dayOfWeek of week" class="AvailabilityListMobile-calendar-week-day">
          <div class="AvailabilityListMobile-calendar-week-day-hours">
            <div *ngFor="let hour of hours" class="AvailabilityListMobile-calendar-week-day-hours-item">
              {{ hour }} h
            </div>
          </div>
          <div class="AvailabilityListMobile-calendar-week-day-grid">
            <div *ngFor="let hour of hours" class="AvailabilityListMobile-calendar-week-day-grid-hour"></div>
            <ng-container *ngIf="getSlotsFromDay(dayOfWeek) as slotsForDay">
              <ng-container *ngTemplateOutlet="slotsForDayTemplate; context: {
              dayOfWeek: dayOfWeek,
              slotsForDay: slotsForDay,
              firstsCreationSlotsData: getCreationSlotsDataFor(
                dayOfWeek,
                null,
                slotsForDay.length ? slotsForDay[0].from : null
              ),
              lastsCreationSlotsData: slotsForDay.length
                ? getCreationSlotsDataFor(dayOfWeek, slotsForDay[slotsForDay.length - 1].to, null)
                : []
            }"/>
            </ng-container>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<!-- //////////////////////////////////////////////////////////////////////////////////////////////////// -->
<!-- ////////////////////////////////////////// FOR DESKTOP VIEW  //////////////////////////////////////// -->
<!-- //////////////////////////////////////////////////////////////////////////////////////////////////// -->
<div
  *ngIf="!isMobile"
  class="AvailabilityListDesktop-calendar"
>
  <div class="AvailabilityListDesktop-calendar-days">
    <div class="AvailabilityListDesktop-calendar-days-hours"><!-- Top of column --></div>
    <div *ngFor="let dayOfWeek of week" class="AvailabilityListDesktop-calendar-days-item">
      {{ DateHelper.format(dayOfWeek, DateFormat.MEDIUM_DATE) }}
    </div>
    <div class="AvailabilityListDesktop-calendar-days-scrollbar"></div>
  </div>

  <div class="AvailabilityListDesktop-calendar-week">
    <div class="AvailabilityListDesktop-calendar-week-hours">
      <div *ngFor="let hour of hours" class="AvailabilityListDesktop-calendar-week-hours-item">
        {{ hour }} h
      </div>
    </div>

    <div class="AvailabilityListDesktop-calendar-week-grid" #gridDesktopComponent tabindex="0">
      <div *ngFor="let dayOfWeek of week" class="AvailabilityListDesktop-calendar-week-grid-day">
        <div *ngFor="let hour of hours" class="AvailabilityListDesktop-calendar-week-grid-day-hour"></div>
        <ng-container *ngIf="getSlotsFromDay(dayOfWeek) as slotsForDay">
          <ng-container *ngTemplateOutlet="slotsForDayTemplate; context: {
            dayOfWeek: dayOfWeek,
            slotsForDay: slotsForDay,
            firstsCreationSlotsData: getCreationSlotsDataFor(
              dayOfWeek,
              null,
              slotsForDay.length ? slotsForDay[0].from : null
            ),
            lastsCreationSlotsData: slotsForDay.length
              ? getCreationSlotsDataFor(dayOfWeek, slotsForDay[slotsForDay.length - 1].to, null)
              : []
          }"/>
        </ng-container>
      </div>
    </div>
  </div>
</div>

<op-availability-edit
  *ngIf="editingSlot"
  [slot]="editingSlot"
  (cancelled)="onCancelEdit()"
  (slotEdited)="onSlotEditedOrRemoved()"
  (slotRemoved)="onSlotEditedOrRemoved()"
/>

<op-availability-add
  *ngIf="addingAvailability"
  [practitioner]="practitioner"
  [baseDates]="baseDatesForAddingAvailability"
  (cancelAddingAvailability)="onCancelAdd()"
  (availabilityAdded)="onAvailabilityAdded()"
/>


<!-- //////////////////////////////////////////////////////////////////////////////////////////////////// -->
<!-- /////////////////////////////// TEMPLATE for slots list in a specific day ////////////////////////// -->
<!-- //////////////////////////////////////////////////////////////////////////////////////////////////// -->
<ng-template
  #slotsForDayTemplate
  let-dayOfWeek="dayOfWeek"
  let-slotsForDay="slotsForDay"
  let-firstsCreationSlotsData="firstsCreationSlotsData"
  let-lastsCreationSlotsData="lastsCreationSlotsData"
>
  <!-- Empty day -->
  <ng-container *ngIf="slotsForDay.length === 0 && getDefaultSlotDate(dayOfWeek) as defaultSlot">
    <div
      class="AvailabilityList-slot empty"
      [class]="getCssClassesForEmptyDay()"
      [style.cursor]="'pointer'"
      (click)="onAddAvailability(defaultSlot, null)"
    ></div>
  </ng-container>

  <ng-container *ngIf="slotsForDay.length > 0">
    <!-- Firsts creation-slots -->
    <ng-container *ngFor="let creationSlotData of firstsCreationSlotsData">
      <ng-container *ngTemplateOutlet="slotTemplate; context: {
      slot: null,
      from: creationSlotData.from,
      to: creationSlotData.to,
      diff: creationSlotData.diff,
      visible: false
    }"/>
    </ng-container>

    <ng-container *ngFor="let slot of slotsForDay; index as index">
      <!-- Actual created-slot -->
      <ng-container *ngTemplateOutlet="slotTemplate; context: {
      slot: slot,
      from: slot.from,
      to: slot.to,
      diff: DateHelper.getDifferenceOfTimeInMinutes(slot.from, slot.to),
      visible: true
    }"/>

      <!-- In-between creation-slots -->
      <ng-container
        *ngIf="index >= 0
      && index < slotsForDay.length - 1
      && getCreationSlotsDataFor(slot.from, slotsForDay[index].to, slotsForDay[index + 1].from) as inBetweenCreationSlotsData"
      >
        <ng-container *ngFor="let creationSlotData of inBetweenCreationSlotsData">
          <ng-container *ngTemplateOutlet="slotTemplate; context: {
          slot: null,
          from: creationSlotData.from,
          to: creationSlotData.to,
          diff: creationSlotData.diff,
          visible: true
        }"/>
        </ng-container>
      </ng-container>
    </ng-container>

    <!-- Lasts creation-slots -->
    <ng-container *ngFor="let creationSlotData of lastsCreationSlotsData">
      <ng-container *ngTemplateOutlet="slotTemplate; context: {
      slot: null,
      from: creationSlotData.from,
      to: creationSlotData.to,
      diff: creationSlotData.diff,
      visible: false
    }"/>
    </ng-container>
  </ng-container>
</ng-template>


<!-- //////////////////////////////////////////////////////////////////////////////////////////////////// -->
<!-- ///////////////////////// TEMPLATE for a specific created-slot or creation-slot //////////////////// -->
<!-- //////////////////////////////////////////////////////////////////////////////////////////////////// -->
<ng-template
  #slotTemplate
  let-slot="slot"
  let-from="from"
  let-to="to"
  let-diff="diff"
  let-visible="visible"
>
  <div
    class="AvailabilityList-slot p-button"
    (click)="slot ? onEditSlot(slot) : onAddAvailability(from, to)"
    [class]="getCssClassesForSlot(from, to)"
    [ngClass]="{
      'creation': !slot,
      'visible': visible,
      'p-button-primary': slot?.practitioner === Practitioner.ROSE,
      'p-button-help': slot?.practitioner === Practitioner.ANAIS,
      'p-button-outlined': !slot?.hasPatient
    }"
  >
    <!-- Creation-slot -->
    <ng-container *ngIf="!slot">
      <span class="ml-6">{{ DateHelper.parseMinutes(diff) }}</span>
    </ng-container>

    <!-- Created-slot -->
    <ng-container *ngIf="slot">
      <div class="AvailabilityList-slot-details" [ngClass]="{ 'condensed': diff < DEFAULT_SLOT_DURATION }">
        <div *ngIf="diff >= DEFAULT_SLOT_DURATION || !slot.patient">
          <span class="pi pi-clock"></span>
          <span class="ml-8">{{ DateHelper.format(slot.from, DateFormat.TIME) }} • {{ DateHelper.parseMinutes(DateHelper.getDifferenceOfTimeInMinutes(slot.from, slot.to)) }}</span>
        </div>
        <div *ngIf="slot.patient" class="AvailabilityList-slot-details-patient mt-2">
          <span class="pi pi-user"></span>
          <span class="ml-8">{{ slot.patient.lastname }}</span>
          <span *ngIf="diff < DEFAULT_SLOT_DURATION">&nbsp;• {{ DateHelper.parseMinutes(DateHelper.getDifferenceOfTimeInMinutes(slot.from, slot.to)) }}</span>
        </div>
      </div>
      <div *ngIf="diff >= DEFAULT_SLOT_DURATION" class="AvailabilityList-slot-practitioner">
        <op-practitioner-icon [practitioner]="slot.practitioner"/>
      </div>
    </ng-container>
  </div>
</ng-template>

// client2/src/components/admin/AvailabilityList.vue
<template>
  <div class="AvailabilityList-filter">
    <v-btn
      color="primary"
      size="small"
      icon="mdi-arrow-left"
      @click="onPreviousWeek()"
    />
    <Button :outlined="true" @click="onCurrentWeek()">
      Semaine : {{ DateHelper.format(week[0], DateFormat.SHORT_DATE_API) }}
    </Button>
    <v-btn
      color="primary"
      size="small"
      icon="mdi-arrow-right"
      @click="onNextWeek()"
    />
  </div>

  <v-dialog
    v-model="editingSlot"
    max-width="600"
    content-class="w-auto"
    :fullscreen="isMobile"
    :scrollable="isMobile"
  >
    <AvailabilityEdit
      :practitioner="practitioner"
      :slot="slotToBeEdited"
      @cancelled="onCancelEdit()"
      @slot-edited="onSlotEditedOrRemoved()"
      @slot-removed="onSlotEditedOrRemoved()"
    />
  </v-dialog>

  <v-dialog
    v-model="addingAvailability"
    max-width="600"
    content-class="w-auto"
    :fullscreen="isMobile"
    :scrollable="isMobile"
  >
    <AvailabilityAdd
      :practitioner="practitioner"
      :base-dates="baseDatesForAddingAvailability"
      @cancel-adding-availability="onCancelAdd()"
      @availability-added="onAvailabilityAdded()"
    />
  </v-dialog>


  <!-- //////////////////////////////////////////////////////////////////////////////////////////////////// -->
  <!-- ////////////////////////////////////////// FOR MOBILE VIEW  //////////////////////////////////////// -->
  <!-- //////////////////////////////////////////////////////////////////////////////////////////////////// -->
  <div
    v-if="isMobile"
    class="AvailabilityListMobile-container"
  >
    <div class="AvailabilityListMobile-calendar">
      <div class="AvailabilityListMobile-calendar-days">
        <div v-for="dayOfWeek of week" class="AvailabilityListMobile-calendar-days-item">
          {{ DateHelper.format(dayOfWeek, DateFormat.MEDIUM_DATE) }}
        </div>
        <div class="AvailabilityListMobile-calendar-days-scrollbar"></div>
      </div>

      <div class="AvailabilityListMobile-calendar-week">
        <div class="AvailabilityListMobile-calendar-week-container" ref="gridMobileComponent" tabindex="0">
          <div v-for="dayOfWeek of week" class="AvailabilityListMobile-calendar-week-day">
            <div class="AvailabilityListMobile-calendar-week-day-hours">
              <div v-for="hour of hours" class="AvailabilityListMobile-calendar-week-day-hours-item">
                {{ hour }} h
              </div>
            </div>
            <div class="AvailabilityListMobile-calendar-week-day-grid">
              <div v-for="_ of hours" class="AvailabilityListMobile-calendar-week-day-grid-hour"></div>
              <v-progress-circular v-if="isLoadingAvailabilities" indeterminate/>
              <AvailabilityListSlotsForDay
                :day-of-week="dayOfWeek"
                :slots-for-day="getSlotsFromDay(dayOfWeek)"
                @edit-slot="onEditSlot($event)"
                @add-availability="onAddAvailability($event)"
              />
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>


  <!-- //////////////////////////////////////////////////////////////////////////////////////////////////// -->
  <!-- ////////////////////////////////////////// FOR DESKTOP VIEW  //////////////////////////////////////// -->
  <!-- //////////////////////////////////////////////////////////////////////////////////////////////////// -->
  <div v-if="!isMobile" class="AvailabilityListDesktop-calendar">
    <div class="AvailabilityListDesktop-calendar-days">
      <div class="AvailabilityListDesktop-calendar-days-hours"><!-- Top of column --></div>
      <v-progress-circular
        v-if="isLoadingAvailabilities"
        class="position-absolute top-40p left-49p"
        color="primary"
        indeterminate
      />
      <div v-for="dayOfWeek of week" class="AvailabilityListDesktop-calendar-days-item">
        {{ DateHelper.format(dayOfWeek, DateFormat.MEDIUM_DATE) }}
      </div>
      <div class="AvailabilityListDesktop-calendar-days-scrollbar"></div>
    </div>

    <div class="AvailabilityListDesktop-calendar-week">
      <div class="AvailabilityListDesktop-calendar-week-hours">
        <div v-for="hour of hours" class="AvailabilityListDesktop-calendar-week-hours-item">
          {{ hour }} h
        </div>
      </div>

      <div class="AvailabilityListDesktop-calendar-week-grid" ref="gridDesktopComponent" tabindex="0">
        <div v-for="dayOfWeek of week" class="AvailabilityListDesktop-calendar-week-grid-day">
          <div v-for="_ of hours" class="AvailabilityListDesktop-calendar-week-grid-day-hour"></div>
          <AvailabilityListSlotsForDay
            :day-of-week="dayOfWeek"
            :slots-for-day="getSlotsFromDay(dayOfWeek)"
            @edit-slot="onEditSlot($event)"
            @add-availability="onAddAvailability($event)"
          />
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import {Component, Prop, Ref, Vue} from "vue-facing-decorator";
import {Practitioner} from "@shared/types/practitioner.enum";
import {Container} from "typedi";
import AvailabilityHttpService from "@/services/http/availability.http-service";
import type {Availability} from "@shared/types/availability.interface";
import type {SlotPersisted} from "@shared/types/slot.interface";
import DateFormat from "@shared/types/date-format.enum";
import DateHelper from "@shared/helpers/date.helper";
import AvailabilityListSlotsForDay from "@/components/admin/AvailabilityListSlotsForDay.vue";
import AvailabilityAdd from "@/components/admin/AvailabilityAdd.vue";
import AvailabilityEdit from "@/components/admin/AvailabilityEdit.vue";
import Button from "@/components/_design-system/Button.vue";
import ToasterService from "@/services/snackbar/toaster.service";

@Component({
  components: {Button, AvailabilityEdit, AvailabilityAdd, AvailabilityListSlotsForDay}
})
export default class AvailabilityListComponent extends Vue {
  @Prop({required: true}) practitioner!: Practitioner
  @Ref("gridDesktopComponent") gridDesktopComponent!: HTMLElement
  @Ref("gridMobileComponent") gridMobileComponent!: HTMLElement

  private readonly availabilityService = Container.get(AvailabilityHttpService)
  private readonly toasterService = Container.get(ToasterService)

  readonly DateFormat = DateFormat
  readonly DateHelper = DateHelper
  readonly Practitioner = Practitioner

  baseDateForSearch = new Date()
  availabilities: Availability[] = []
  isLoadingAvailabilities = false
  slotToBeEdited: SlotPersisted | null = null
  addingAvailability = false
  baseDatesForAddingAvailability: [Date | null, Date | null] = [null, null]

  get isMobile(): boolean {
    return document.body.clientWidth < 800
  }

  get hours(): number[] {
    return new Array<number>(24).fill(0).map((_, index) => index)
  }

  get week(): Date[] {
    return DateHelper.getWeekFromDate(this.baseDateForSearch)
  }

  get availabilitiesPerWeekDay(): { [dayOfWeek: number]: SlotPersisted[] } {
    const availabilities: { [dayOfWeek: number]: SlotPersisted[] } = {}
    this.week.forEach((dayOfWeek) => {
      availabilities[dayOfWeek.getDay()] = []
    })
    this.availabilities.forEach((availability) => {
      const dayOfWeek = new Date(availability.date).getDay()
      availabilities[dayOfWeek].push(...availability.slots.sort((s1, s2) => s1.from < s2.from ? -1 : 1))
    })
    return availabilities
  }

  get editingSlot(): boolean {
    return this.slotToBeEdited !== null
  }

  mounted() {
    this.loadAvailabilities()
  }

  onAddAvailability({ fromDate, toDate }: { fromDate: string, toDate: string }) {
    if (fromDate) {
      this.baseDatesForAddingAvailability[0] = new Date(fromDate)
    } else {
      this.baseDatesForAddingAvailability[0] = null
    }
    if (toDate) {
      this.baseDatesForAddingAvailability[1] = new Date(toDate)
    } else {
      this.baseDatesForAddingAvailability[1] = null
    }
    this.addingAvailability = true
  }

  onEditSlot(slot: SlotPersisted) {
    this.slotToBeEdited = slot
  }

  onCancelEdit() {
    this.slotToBeEdited = null
  }

  onSlotEditedOrRemoved() {
    this.slotToBeEdited = null
    this.loadAvailabilities()
  }

  onCancelAdd() {
    this.addingAvailability = false
  }

  onAvailabilityAdded() {
    this.addingAvailability = false
    this.loadAvailabilities()
  }

  onPreviousWeek() {
    const newDate = new Date(this.baseDateForSearch)
    newDate.setDate(newDate.getDate() - 7)
    this.baseDateForSearch = newDate
    this.loadAvailabilities()
    this.focusGrid()
  }

  onCurrentWeek() {
    this.baseDateForSearch = new Date()
    this.loadAvailabilities()
    this.focusGrid()
  }

  onNextWeek() {
    const newDate = new Date(this.baseDateForSearch)
    newDate.setDate(newDate.getDate() + 7)
    this.baseDateForSearch = newDate
    this.loadAvailabilities()
    this.focusGrid()
  }

  async loadAvailabilities() {
    if (this.isLoadingAvailabilities) {
      return
    }
    this.isLoadingAvailabilities = true
    const from = this.week[0]
    const to = new Date(from)
    to.setDate(to.getDate() + 7)
    this.availabilities = []

    try {
      this.availabilities = await this.availabilityService.list(from, to)
      this.scrollToMidday()
    } catch {
      this.toasterService.sendToast({
        type: "error",
        message: "Impossible de récupérer les créneaux",
      })
    } finally {
      this.isLoadingAvailabilities = false
    }
  }

  getSlotsFromDay(dayOfWeek: Date): SlotPersisted[] {
    return this.availabilitiesPerWeekDay[dayOfWeek.getDay()]
  }

  focusGrid() {
    if (this.isMobile) {
      this.gridMobileComponent.focus()
    } else {
      this.gridDesktopComponent.focus()
    }
  }

  scrollToMidday() {
    if (!this.isMobile) {
      this.gridDesktopComponent.parentElement?.scrollTo(0, 60 * 11)
    }
  }
}
</script>
